import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Soul Brokers',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="antialiased flex flex-col bg-gray-300">{children}</body>
    </html>
  )
}
